import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'
import { getUserFromRequest } from '@/lib/api/getUser'

// Event-scoped authorization: the session's primary host, or an event
// owner/admin/moderator (via event_members). Replaces the pre-multi-tenant
// global profile admin flag check.
const MANAGER_ROLES = ['owner', 'admin', 'moderator']

async function canManageSession(
  admin: Awaited<ReturnType<typeof createAdminClient>>,
  session: { host_id: string | null; event_id: string },
  userId: string
): Promise<boolean> {
  if (session.host_id === userId) return true
  const { data: membership } = await admin
    .from('event_members')
    .select('role')
    .eq('event_id', session.event_id)
    .eq('user_id', userId)
    .maybeSingle()
  return !!membership && MANAGER_ROLES.includes(membership.role)
}

// POST /api/sessions/[id]/invites — Create a new invite link
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: sessionId } = await params

  const user = await getUserFromRequest(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = await createAdminClient()

  // Verify caller is primary host or an event manager
  const { data: session } = await admin
    .from('sessions')
    .select('id, host_id, event_id')
    .eq('id', sessionId)
    .single()

  if (!session) {
    return NextResponse.json({ error: 'Session not found' }, { status: 404 })
  }

  if (!(await canManageSession(admin, session, user.id))) {
    return NextResponse.json({ error: 'Only the primary host or an event admin can create invites' }, { status: 403 })
  }

  // Create invite (token is auto-generated by DB default)
  const { data: invite, error } = await admin
    .from('cohost_invites')
    .insert({
      session_id: sessionId,
      event_id: session.event_id,
      created_by: user.id,
    })
    .select('id, token, expires_at, created_at')
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(invite, { status: 201 })
}

// GET /api/sessions/[id]/invites — List invites for a session
export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id: sessionId } = await params

  const user = await getUserFromRequest(request)
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = await createAdminClient()

  // Verify caller is primary host or an event manager
  const { data: session } = await admin
    .from('sessions')
    .select('id, host_id, event_id')
    .eq('id', sessionId)
    .single()

  if (!session) {
    return NextResponse.json({ error: 'Session not found' }, { status: 404 })
  }

  if (!(await canManageSession(admin, session, user.id))) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const { data: invites, error } = await admin
    .from('cohost_invites')
    .select('id, token, status, expires_at, created_at, accepted_at, accepted_by, created_by')
    .eq('session_id', sessionId)
    .order('created_at', { ascending: false })

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(invites)
}
