import 'server-only'
/**
 * Post-session feedback on ballot machinery (plan §6 item 23), modelled on Free School's
 * `apps/appview/src/lib/feedback.ts`, with one difference: a participant may change or
 * withdraw their feedback while the window is open.
 *
 *   feedback_windows   per session, opened when its slot starts, closing
 *                      FEEDBACK_WINDOW_HOURS after it ends. `ballot_key` (generated by
 *                      the database) is DESTROYED at close.
 *   feedback_ballots   (session, hmac(ballot_key, account_id)) — "this person left
 *                      feedback, once". No account column, no link to content.
 *   feedback_entries   (id, rating, would_attend_again, comment, DAY) — no author, no
 *                      ballot column, a date not a timestamp.
 *
 * Editability without an author column: while the window is open an entry's id is
 * derived from the key, `uuid(hmac(ballot_key, 'entry:' || account_id)[0:16])`, so the
 * server can find the caller's own entry and nobody can read the mapping without the key.
 * At close every entry is re-inserted with a fresh random id in random order and the key
 * is set NULL: from then on no entry can be tied to its author, to its ballot, or to the
 * order it was written in — not by us, not with the whole disk.
 *
 * Summaries are computed once, at close. Nothing is shown while a window is open (a live
 * average would let a host watching the room difference out one person's rating); after
 * close the numbers need k entries, and comments reach hosts/organizers only then.
 */
import { sql, tx, type Sql } from '@/lib/db'
import type postgres from 'postgres'
import { VotingError } from './errors'
import { eventK, isUuid } from './rounds'

/** Feedback stays open this long after a session ends. */
export const FEEDBACK_WINDOW_HOURS = 72
export const MAX_FEEDBACK_COMMENT = 2000

export type FeedbackWindowStatus = 'none' | 'open' | 'closed'

export interface FeedbackInput {
  rating: number
  wouldAttendAgain?: boolean | null
  comment?: string | null
}

export interface OwnFeedback {
  rating: number
  would_attend_again: boolean | null
  comment: string | null
}

export interface FeedbackWindowInfo {
  status: FeedbackWindowStatus
  opensAt: string | null
  closesAt: string | null
}

export interface FeedbackSummary extends FeedbackWindowInfo {
  k: number
  /** True when the window is closed and at least k people left feedback. */
  released: boolean
  count?: number
  avgRating?: number
  wouldAttendAgain?: { yes: number; no: number }
  /** Verbatim comments, in random order, without ratings or dates. Only when requested, closed and released. */
  comments?: string[]
}

interface StoredSummary {
  count: number
  avgRating: number | null
  wouldAttendAgain: { yes: number; no: number }
}

interface WindowRow {
  session_id: string
  event_id: string
  opens_at: string
  closes_at: string
  finalized_at: string | null
  summary: StoredSummary | null
  now: string
}

/** Validate and normalize user input; throws 400 with the offending field. */
export function parseFeedbackInput(body: unknown): FeedbackInput {
  const b = body && typeof body === 'object' ? (body as Record<string, unknown>) : {}
  const rating = Number(b.rating)
  if (!Number.isInteger(rating) || rating < 1 || rating > 5) {
    throw new VotingError('Rating must be a whole number from 1 to 5', 400, 'InvalidFeedback', 'rating')
  }
  let comment: string | null = null
  if (b.comment !== undefined && b.comment !== null) {
    if (typeof b.comment !== 'string') throw new VotingError('Comment must be text', 400, 'InvalidFeedback', 'comment')
    comment = b.comment.trim() || null
    if (comment && comment.length > MAX_FEEDBACK_COMMENT) {
      throw new VotingError(`Comment must be ${MAX_FEEDBACK_COMMENT} characters or fewer`, 400, 'InvalidFeedback', 'comment')
    }
  }
  const raw = b.wouldAttendAgain ?? b.would_attend_again
  let wouldAttendAgain: boolean | null = null
  if (raw !== undefined && raw !== null) {
    if (typeof raw !== 'boolean') {
      throw new VotingError('would_attend_again must be true, false or null', 400, 'InvalidFeedback', 'would_attend_again')
    }
    wouldAttendAgain = raw
  }
  return { rating, comment, wouldAttendAgain }
}

/**
 * The scheduled sessions whose feedback window should exist now, as a SELECT source:
 * started, and not ended more than FEEDBACK_WINDOW_HOURS ago.
 */
function dueWindowSource(t: Sql, sessionId?: string) {
  return t`
    select x.id as session_id, x.event_id, x.starts_at as opens_at,
           greatest(x.ends_at, x.starts_at + interval '1 minute') + make_interval(hours => ${FEEDBACK_WINDOW_HOURS}) as closes_at
    from (
      select s.id, s.event_id,
             case when s.is_self_hosted then s.self_hosted_start_time else ts.start_time end as starts_at,
             case when s.is_self_hosted
                  then coalesce(s.self_hosted_end_time, s.self_hosted_start_time + make_interval(mins => coalesce(s.duration, 60)))
                  else ts.end_time end as ends_at
      from sessions s
      join events e on e.id = s.event_id
      left join time_slots ts on ts.id = s.time_slot_id
      where s.status = 'scheduled' and e.status <> 'draft'
        ${sessionId ? t`and s.id = ${sessionId}` : t``}
    ) x
    where x.starts_at is not null and x.starts_at <= now()
      and greatest(x.ends_at, x.starts_at + interval '1 minute') + make_interval(hours => ${FEEDBACK_WINDOW_HOURS}) > now()
  `
}

/**
 * Open the session's feedback window if its slot has started (and it has not already
 * been opened). Never regenerates a key: a second call is a no-op, and a closed window
 * stays closed. Returns the window, or null when the session has not started.
 */
export async function openFeedbackWindow(sessionId: string, db?: Sql): Promise<FeedbackWindowInfo | null> {
  if (!isUuid(sessionId)) return null
  const d = db ?? sql
  await d`
    insert into feedback_windows (session_id, event_id, opens_at, closes_at)
    ${dueWindowSource(d, sessionId)}
    on conflict (session_id) do nothing
  `
  const [row] = await d<WindowRow[]>`
    select session_id, event_id, opens_at, closes_at, finalized_at, summary, now() as now
    from feedback_windows where session_id = ${sessionId}
  `
  return row ? windowInfo(row) : null
}

function windowInfo(row: WindowRow | undefined): FeedbackWindowInfo {
  if (!row) return { status: 'none', opensAt: null, closesAt: null }
  const closed = !!row.finalized_at || new Date(row.now).getTime() >= new Date(row.closes_at).getTime()
  return { status: closed ? 'closed' : 'open', opensAt: row.opens_at, closesAt: row.closes_at }
}

/** Load (lazily opening) the window for a session, locked FOR SHARE inside `t`. */
async function lockOpenWindow(t: postgres.TransactionSql, sessionId: string): Promise<WindowRow> {
  await openFeedbackWindow(sessionId, t)
  const [row] = await t<WindowRow[]>`
    select session_id, event_id, opens_at, closes_at, finalized_at, summary, now() as now
    from feedback_windows where session_id = ${sessionId}
    for share
  `
  if (!row) throw new VotingError('Feedback opens once the session has started', 409, 'WindowNotOpen')
  if (row.finalized_at || new Date(row.now).getTime() >= new Date(row.closes_at).getTime()) {
    throw new VotingError('The feedback window for this session has closed', 409, 'WindowClosed')
  }
  return row
}

/** SQL for the caller's derived entry id under the window's key (valid only while open). */
function entryIdSql(t: Sql, accountId: string) {
  return t`encode(substring(extensions.hmac(convert_to('entry:' || ${accountId}::text, 'UTF8'), w.ballot_key, 'sha256') from 1 for 16), 'hex')::uuid`
}

function tokenSql(t: Sql, accountId: string) {
  return t`extensions.hmac(convert_to(${accountId}::text, 'UTF8'), w.ballot_key, 'sha256')`
}

/**
 * Leave or change the caller's feedback on a session while its window is open: one
 * ballot per account per session, mutable until close. The caller must be a member of
 * the event and not a host or co-host of the session.
 */
export async function submitFeedback(accountId: string, sessionId: string, input: FeedbackInput): Promise<OwnFeedback> {
  if (!isUuid(accountId)) throw new VotingError('Sign in to leave feedback', 401, 'NotEligible')
  if (!isUuid(sessionId)) throw new VotingError('Session not found', 404, 'NotFound')
  const clean = parseFeedbackInput({
    rating: input.rating,
    comment: input.comment ?? null,
    wouldAttendAgain: input.wouldAttendAgain ?? null,
  })

  return tx(async (t) => {
    const win = await lockOpenWindow(t, sessionId)
    const [who] = await t<{ role: string | null; is_host: boolean }[]>`
      select (select m.role from event_members m where m.event_id = s.event_id and m.user_id = ${accountId}) as role,
             (s.host_id = ${accountId}
               or exists (select 1 from session_cohosts c where c.session_id = s.id and c.user_id = ${accountId})) as is_host
      from sessions s where s.id = ${sessionId}
    `
    if (!who?.role) throw new VotingError('Join the gathering before leaving feedback', 403, 'NotEligible')
    if (who.is_host) throw new VotingError('Hosts cannot leave feedback on their own session', 403, 'SelfFeedback')

    await t`
      insert into feedback_ballots (session_id, event_id, token)
      select w.session_id, w.event_id, ${tokenSql(t, accountId)}
      from feedback_windows w
      where w.session_id = ${win.session_id} and w.ballot_key is not null
      on conflict (session_id, token) do nothing
    `
    const [entry] = await t<OwnFeedback[]>`
      insert into feedback_entries (id, session_id, event_id, rating, would_attend_again, comment, day)
      select ${entryIdSql(t, accountId)}, w.session_id, w.event_id,
             ${clean.rating}, ${clean.wouldAttendAgain ?? null}, ${clean.comment ?? null},
             (now() at time zone 'UTC')::date
      from feedback_windows w
      where w.session_id = ${win.session_id} and w.ballot_key is not null
      on conflict (id) do update
        set rating = excluded.rating,
            would_attend_again = excluded.would_attend_again,
            comment = excluded.comment,
            day = excluded.day
      returning rating, would_attend_again, comment
    `
    if (!entry) throw new VotingError('The feedback window for this session has closed', 409, 'WindowClosed')
    return entry
  })
}

/** The caller's own feedback while the window is open; null otherwise (after close nobody can find it). */
export async function getOwnFeedback(accountId: string, sessionId: string): Promise<OwnFeedback | null> {
  if (!isUuid(accountId) || !isUuid(sessionId)) return null
  const [row] = await sql<OwnFeedback[]>`
    select f.rating, f.would_attend_again, f.comment
    from feedback_windows w
    join feedback_entries f on f.session_id = w.session_id and f.id = ${entryIdSql(sql, accountId)}
    where w.session_id = ${sessionId} and w.ballot_key is not null and w.closes_at > now()
  `
  return row ?? null
}

/** Withdraw the caller's feedback while the window is open (their ballot goes too). */
export async function retractFeedback(accountId: string, sessionId: string): Promise<{ removed: boolean }> {
  if (!isUuid(accountId) || !isUuid(sessionId)) throw new VotingError('Session not found', 404, 'NotFound')
  return tx(async (t) => {
    const [row] = await t<WindowRow[]>`
      select session_id, event_id, opens_at, closes_at, finalized_at, summary, now() as now
      from feedback_windows where session_id = ${sessionId}
      for share
    `
    if (!row) return { removed: false }
    if (row.finalized_at || new Date(row.now).getTime() >= new Date(row.closes_at).getTime()) {
      throw new VotingError('Feedback is sealed once the window closes', 409, 'WindowClosed')
    }
    const removed = await t`
      delete from feedback_entries f
      using feedback_windows w
      where w.session_id = ${sessionId} and w.ballot_key is not null
        and f.session_id = w.session_id and f.id = ${entryIdSql(t, accountId)}
    `
    await t`
      delete from feedback_ballots b
      using feedback_windows w
      where w.session_id = ${sessionId} and w.ballot_key is not null
        and b.session_id = w.session_id and b.token = ${tokenSql(t, accountId)}
    `
    return { removed: removed.count > 0 }
  })
}

/** Close one window: re-key entries at random, freeze the aggregate, destroy the key. */
async function closeFeedbackWindow(sessionId: string): Promise<boolean> {
  return tx(async (t) => {
    const [row] = await t<{ session_id: string }[]>`
      select session_id from feedback_windows
      where session_id = ${sessionId} and finalized_at is null and closes_at <= now()
      for update
    `
    if (!row) return false
    await t`
      with sealed as (
        delete from feedback_entries where session_id = ${sessionId}
        returning session_id, event_id, rating, would_attend_again, comment, day
      )
      insert into feedback_entries (id, session_id, event_id, rating, would_attend_again, comment, day)
      select gen_random_uuid(), session_id, event_id, rating, would_attend_again, comment, day
      from sealed
      order by extensions.gen_random_bytes(16)
    `
    await t`
      update feedback_windows w
      set ballot_key = null,
          finalized_at = now(),
          summary = (
            select jsonb_build_object(
              'count', count(*)::int,
              'avgRating', round(avg(f.rating)::numeric, 2),
              'wouldAttendAgain', jsonb_build_object(
                'yes', count(*) filter (where f.would_attend_again is true)::int,
                'no', count(*) filter (where f.would_attend_again is false)::int
              )
            )
            from feedback_entries f where f.session_id = w.session_id
          )
      where w.session_id = ${sessionId}
    `
    return true
  })
}

/**
 * The job sweep: open windows for sessions whose slot has started, close windows whose
 * time is up.
 */
export async function closeDueFeedbackWindows(): Promise<{ opened: number; closed: number }> {
  const opened = await sql`
    insert into feedback_windows (session_id, event_id, opens_at, closes_at)
    ${dueWindowSource(sql)}
    on conflict (session_id) do nothing
  `
  const due = await sql<{ session_id: string }[]>`
    select session_id from feedback_windows where finalized_at is null and closes_at <= now()
  `
  let closed = 0
  for (const { session_id } of due) {
    if (await closeFeedbackWindow(session_id)) closed++
  }
  return { opened: opened.count, closed }
}

/**
 * The feedback summary for a session. Nothing while the window is open. After close:
 * count, average rating and would-attend-again counts when at least k people left
 * feedback; with `includeComments` (hosts, co-hosts and organizers only — the caller
 * authorizes) the comments too, verbatim, in random order, without ratings or dates.
 */
export async function feedbackSummary(
  sessionId: string,
  k?: number,
  options: { includeComments?: boolean } = {},
): Promise<FeedbackSummary> {
  if (!isUuid(sessionId)) return { status: 'none', opensAt: null, closesAt: null, k: k ?? 3, released: false }
  const [row] = await sql<WindowRow[]>`
    select session_id, event_id, opens_at, closes_at, finalized_at, summary, now() as now
    from feedback_windows where session_id = ${sessionId}
  `
  if (row && !row.finalized_at && new Date(row.now).getTime() >= new Date(row.closes_at).getTime()) {
    await closeFeedbackWindow(sessionId)
    return feedbackSummary(sessionId, k, options)
  }
  const info = windowInfo(row)
  const threshold = k ?? (row ? await eventK(row.event_id) : 3)
  if (!row || !row.finalized_at || !row.summary) return { ...info, k: threshold, released: false }

  const stored = row.summary
  if (stored.count < threshold) return { ...info, k: threshold, released: false }
  const summary: FeedbackSummary = {
    ...info,
    k: threshold,
    released: true,
    count: stored.count,
    avgRating: stored.avgRating === null ? undefined : Number(stored.avgRating),
    wouldAttendAgain: stored.wouldAttendAgain,
  }
  if (options.includeComments) {
    const comments = await sql<{ comment: string }[]>`
      select comment from feedback_entries
      where session_id = ${sessionId} and comment is not null
      order by id
    `
    summary.comments = comments.map((c) => c.comment)
  }
  return summary
}
