import 'server-only'
/**
 * Voting rounds: open, close, and every read of their outcome (spec §5.3).
 *
 * The one rule this module exists to keep: **no count leaves the database while a
 * round is open** — not to attendees, not to organizers. Every read of results goes
 * through `resolveClosedRound`, which throws `RoundOpenError` for a round that has
 * not been finalized.
 *
 * Closing (`closeRound`) is one transaction:
 *   1. lock the round (setAllocation holds FOR SHARE on it, so in-flight writes finish
 *      first and later writes see it closed)
 *   2. one `vote_ballots` row per participant: token = hmac-sha256(ballot_key, account_id)
 *   3. explode each ledger's allocation into `vote_entries` in randomized order, with
 *      `day` (UTC date) only and the same token
 *   4. compute `vote_round_results`
 *   5. DELETE the ledger rows, SET ballot_key = NULL, finalized_at = now()
 * The ballot key is generated by the database and only ever read inside those SQL
 * statements: it never reaches application memory.
 *
 * The tally is published as the gathering best-effort AFTER commit (never inside the
 * transaction): see `publishRoundTally`.
 */
import { sql, tx, type Sql } from '@/lib/db'
import { DEFAULT_POLICY_THRESHOLDS } from '@/lib/events/policy'
import type postgres from 'postgres'
import { RoundOpenError, VotingError } from './errors'
import { isMechanism, isPhase, type RoundPhase, type VotingMechanism } from './mechanism'

/* ─────────────────────────────── types ─────────────────────────────── */

export type RoundStatus = 'none' | 'upcoming' | 'open' | 'closed'

/** A round as anyone may see it: rules and window, never a count, never the key. */
export interface RoundInfo {
  id: string
  eventId: string
  phase: RoundPhase
  mechanism: VotingMechanism
  credits: number
  opensAt: string
  closesAt: string
  finalizedAt: string | null
  status: Exclude<RoundStatus, 'none'>
}

export interface RoundStateResult {
  round: RoundInfo | null
  status: RoundStatus
}

export interface SessionResult {
  sessionId: string
  voters: number
  votes: number
  credits: number
}

export interface SchedulingInputs {
  /** The finalized round these inputs come from; null when the event never had one. */
  roundId: string | null
  /** Per session: total votes and the ballot tokens (hex) that named it. Tokens name nobody. */
  bySession: Map<string, { votes: number; tokens: Set<string> }>
}

export type TallyEntry =
  | { sessionId: string; suppressed: true }
  | { sessionId: string; suppressed: false; voters: number; votes: number; credits: number }

export interface PublicTally {
  round: RoundInfo
  /** The suppression threshold this tally is held to. */
  k: number
  /** Distinct participants in the round: a count, never a list. */
  ballotsCast: number
  /** Every session that was votable at close, ordered by session id; under-k entries carry no counts. */
  entries: TallyEntry[]
}

export interface OpenRoundOptions {
  phase?: RoundPhase
  mechanism?: VotingMechanism
  credits?: number
  opensAt?: Date | string
  closesAt?: Date | string
}

export interface CloseRoundOptions {
  /**
   * Publish the tally record as the gathering after commit:
   * 'await' (default) waits for it, 'background' fires and forgets, false skips.
   * Publication is always best-effort: its failure never undoes the close.
   */
  publish?: 'await' | 'background' | false
}

export interface CloseRoundResult {
  roundId: string
  eventId: string
  phase: RoundPhase
  /** false when the round was already finalized (idempotent no-op). */
  closed: boolean
  ballotsCast: number
  entries: number
  /** Publication outcome when `publish` was 'await'. */
  published?: { ok: boolean; error?: string }
}

/* ─────────────────────────────── rows ─────────────────────────────── */

interface RoundRow {
  id: string
  event_id: string
  phase: string
  mechanism: string
  credits: number
  opens_at: string
  closes_at: string
  finalized_at: string | null
}

/** Columns selected for a round. `ballot_key` is deliberately absent everywhere. */
const ROUND_COLUMNS = (t: Sql) => t`r.id, r.event_id, r.phase, r.mechanism, r.credits, r.opens_at, r.closes_at, r.finalized_at`

/**
 * Event statuses during which a round of each phase stays unfinalized. Leaving them
 * closes the round (sweep). `proposals_open` keeps a pre-event round alive because the
 * lifecycle's "Reopen proposals (pause voting)" is reversible: pausing must not seal
 * and discard every ballot. Writes are accepted only in `WRITABLE_STATUS`.
 */
export const KEEP_OPEN_STATUSES: Readonly<Record<RoundPhase, readonly string[]>> = {
  'pre-event': ['voting_open', 'proposals_open'],
  attendance: ['live'],
}

/** The event status in which a round of each phase accepts allocations. */
export const WRITABLE_STATUS: Readonly<Record<RoundPhase, string>> = {
  'pre-event': 'voting_open',
  attendance: 'live',
}

function statusOf(row: RoundRow, now = Date.now()): Exclude<RoundStatus, 'none'> {
  if (row.finalized_at) return 'closed'
  return now < new Date(row.opens_at).getTime() ? 'upcoming' : 'open'
}

export function toRoundInfo(row: RoundRow, now = Date.now()): RoundInfo {
  return {
    id: row.id,
    eventId: row.event_id,
    phase: row.phase as RoundPhase,
    mechanism: row.mechanism as VotingMechanism,
    credits: row.credits,
    opensAt: row.opens_at,
    closesAt: row.closes_at,
    finalizedAt: row.finalized_at,
    status: statusOf(row, now),
  }
}

function toDate(value: Date | string | null | undefined, label: string): Date | null {
  if (value === null || value === undefined || value === '') return null
  const d = value instanceof Date ? value : new Date(value)
  if (Number.isNaN(d.getTime())) throw new VotingError(`${label} is not a valid date`, 400, 'InvalidRound', label)
  return d
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID.test(value)
}

/* ─────────────────────────────── policy ─────────────────────────────── */

/** The event's k (`events.policy_thresholds.feedbackK`), default 3, never below 1. */
export async function eventK(eventId: string, db: Sql = sql): Promise<number> {
  const rows = await db<{ k: number | null }[]>`
    select case when (policy_thresholds->>'feedbackK') ~ '^[0-9]+$'
                then (policy_thresholds->>'feedbackK')::int end as k
    from events where id = ${eventId}
  `
  const k = rows[0]?.k
  return Number.isInteger(k) && (k as number) >= 1 ? (k as number) : DEFAULT_POLICY_THRESHOLDS.feedbackK
}

/* ─────────────────────────────── open ─────────────────────────────── */

/**
 * Open the event's round for `phase` (default 'pre-event'). Package A calls this from
 * the lifecycle transition into `voting_open`; pass the transition's transaction as `db`
 * to open the round atomically with the status change.
 *
 * Defaults come from the event: `voting_mechanism`, `vote_credits_per_user`,
 * `voting_opens_at` (else now), `voting_closes_at` (else the event's start date at
 * 00:00 UTC, else 7 days after opening).
 *
 * Idempotent per (event, phase): when an unfinalized round already exists it is
 * returned — updated to the new rules and window if nobody has allocated yet, or with
 * only `closes_at` moved if somebody has (changing mechanism or credits under existing
 * ballots would invalidate them). A finalized round is never reopened; a new round is
 * created instead.
 */
export async function openRound(
  eventId: string,
  options: OpenRoundOptions = {},
  db?: postgres.TransactionSql,
): Promise<RoundInfo> {
  const run = (t: postgres.TransactionSql) => openRoundIn(t, eventId, options)
  return db ? run(db) : tx(run)
}

async function openRoundIn(t: postgres.TransactionSql, eventId: string, options: OpenRoundOptions): Promise<RoundInfo> {
  const [event] = await t<{
    id: string; voting_mechanism: string | null; vote_credits_per_user: number | null
    voting_opens_at: string | null; voting_closes_at: string | null; start_date: string; now: string
  }[]>`
    select id, voting_mechanism, vote_credits_per_user, voting_opens_at, voting_closes_at, start_date, now() as now
    from events where id = ${eventId} for share
  `
  if (!event) throw new VotingError('Event not found', 404, 'NotFound')

  const phase = options.phase ?? 'pre-event'
  if (!isPhase(phase)) throw new VotingError('phase must be pre-event or attendance', 400, 'InvalidRound', 'phase')
  const mechanism = options.mechanism ?? event.voting_mechanism ?? 'quadratic'
  if (!isMechanism(mechanism)) throw new VotingError('mechanism must be quadratic, linear or approval', 400, 'InvalidRound', 'mechanism')
  const credits = options.credits ?? event.vote_credits_per_user ?? 100
  if (!Number.isInteger(credits) || credits <= 0) {
    throw new VotingError('credits must be a positive whole number', 400, 'InvalidRound', 'credits')
  }

  const now = new Date(event.now)
  const opensAt = toDate(options.opensAt, 'opensAt') ?? toDate(event.voting_opens_at, 'voting_opens_at') ?? now
  let closesAt = toDate(options.closesAt, 'closesAt') ?? toDate(event.voting_closes_at, 'voting_closes_at')
  if (!closesAt) {
    const start = new Date(`${event.start_date}T00:00:00Z`)
    closesAt = start.getTime() > opensAt.getTime() ? start : new Date(opensAt.getTime() + 7 * 86_400_000)
  }
  if (closesAt.getTime() <= opensAt.getTime()) {
    throw new VotingError('Voting must close after it opens', 400, 'InvalidRound', 'closesAt')
  }
  if (closesAt.getTime() <= now.getTime()) {
    throw new VotingError('Voting must close in the future', 400, 'InvalidRound', 'closesAt')
  }

  const [existing] = await t<(RoundRow & { has_ballots: boolean })[]>`
    select ${ROUND_COLUMNS(t)},
           exists (select 1 from credit_ledger l where l.round_id = r.id) as has_ballots
    from vote_rounds r
    where r.event_id = ${eventId} and r.phase = ${phase} and r.finalized_at is null
    for update of r
  `
  if (existing) {
    const [row] = existing.has_ballots
      ? await t<RoundRow[]>`
          update vote_rounds r set closes_at = ${closesAt}
          where r.id = ${existing.id}
          returning ${ROUND_COLUMNS(t)}
        `
      : await t<RoundRow[]>`
          update vote_rounds r
          set mechanism = ${mechanism}, credits = ${credits}, opens_at = ${opensAt}, closes_at = ${closesAt}
          where r.id = ${existing.id}
          returning ${ROUND_COLUMNS(t)}
        `
    return toRoundInfo(row, now.getTime())
  }

  const [row] = await t<RoundRow[]>`
    insert into vote_rounds as r (event_id, phase, mechanism, credits, opens_at, closes_at)
    values (${eventId}, ${phase}, ${mechanism}, ${credits}, ${opensAt}, ${closesAt})
    returning ${ROUND_COLUMNS(t)}
  `
  return toRoundInfo(row, now.getTime())
}

/* ─────────────────────────────── close ─────────────────────────────── */

/**
 * Finalize one round (spec §5.3 step 4) in ONE transaction, then publish its tally
 * best-effort. Idempotent: a finalized round returns `closed: false`.
 */
export async function closeRound(roundId: string, options: CloseRoundOptions = {}): Promise<CloseRoundResult> {
  if (!isUuid(roundId)) throw new VotingError('Voting round not found', 404, 'NotFound')
  const result = await tx(async (t) => {
    const [round] = await t<RoundRow[]>`
      select ${ROUND_COLUMNS(t)} from vote_rounds r where r.id = ${roundId} for update
    `
    if (!round) throw new VotingError('Voting round not found', 404, 'NotFound')
    const base = { roundId: round.id, eventId: round.event_id, phase: round.phase as RoundPhase }
    if (round.finalized_at) {
      const [counts] = await t<{ ballots: number; entries: number }[]>`
        select (select count(*) from vote_ballots where round_id = ${roundId})::int as ballots,
               (select count(*) from vote_entries where round_id = ${roundId})::int as entries
      `
      return { ...base, closed: false, ballotsCast: counts.ballots, entries: counts.entries }
    }

    // 2. Ballots — one per participant whose allocation names a still-votable session.
    //    The token is computed next to the key, in SQL, in random order.
    const ballots = await t`
      insert into vote_ballots (round_id, event_id, token, cast_at)
      select r.id, r.event_id,
             extensions.hmac(convert_to(p.account_id::text, 'UTF8'), r.ballot_key, 'sha256'),
             now()
      from (
        select distinct l.account_id
        from credit_ledger l
        cross join lateral jsonb_each_text(l.allocated) a
        cross join lateral (select case when a.value ~ '^[0-9]{1,6}$' then a.value::int else 0 end as votes) v
        join sessions s on s.event_id = l.event_id and s.id::text = a.key
        where l.round_id = ${roundId} and v.votes > 0
          and s.status in ('approved', 'scheduled') and s.is_votable
      ) p
      cross join vote_rounds r
      where r.id = ${roundId}
      order by extensions.gen_random_bytes(16)
    `

    // 3. Entries — the allocations exploded, randomized, day only, no account.
    const entries = await t`
      insert into vote_entries (round_id, event_id, session_id, votes, credits, day, ballot_token)
      select r.id, r.event_id, s.id, v.votes,
             case r.mechanism when 'quadratic' then v.votes * v.votes when 'linear' then v.votes else 1 end,
             (l.updated_at at time zone 'UTC')::date,
             extensions.hmac(convert_to(l.account_id::text, 'UTF8'), r.ballot_key, 'sha256')
      from credit_ledger l
      join vote_rounds r on r.id = l.round_id
      cross join lateral jsonb_each_text(l.allocated) a
      cross join lateral (select case when a.value ~ '^[0-9]{1,6}$' then a.value::int else 0 end as votes) v
      join sessions s on s.event_id = l.event_id and s.id::text = a.key
      where l.round_id = ${roundId} and v.votes > 0
        and s.status in ('approved', 'scheduled') and s.is_votable
      order by extensions.gen_random_bytes(16)
    `

    // 4. Results — every session votable at close (zero voters included, so a
    //    suppressed public entry never reveals "at least one vote").
    await t`
      insert into vote_round_results (round_id, event_id, session_id, voters, votes, credits)
      select ${roundId}, s.event_id, s.id,
             count(distinct e.ballot_token)::int,
             coalesce(sum(e.votes), 0)::int,
             coalesce(sum(e.credits), 0)::int
      from sessions s
      left join vote_entries e on e.session_id = s.id and e.round_id = ${roundId}
      where s.event_id = ${round.event_id}
        and ((s.status in ('approved', 'scheduled') and s.is_votable) or e.id is not null)
      group by s.event_id, s.id
    `

    // 5. Destroy the linkage.
    await t`delete from credit_ledger where round_id = ${roundId}`
    await t`
      update vote_rounds
      set ballot_key = null,
          finalized_at = now(),
          closes_at = case when closes_at > now() then greatest(now(), opens_at + interval '1 millisecond') else closes_at end
      where id = ${roundId}
    `
    return { ...base, closed: true, ballotsCast: ballots.count, entries: entries.count }
  })

  const mode = options.publish ?? 'await'
  if (result.closed && mode) {
    const publication = publishRoundTally(result.eventId, result.roundId, result.phase)
    if (mode === 'await') return { ...result, published: await publication }
    void publication
  }
  return result
}

/**
 * Publish the closed round's k-suppressed tally as the gathering. Best-effort: never
 * throws. Skipped (ok) for events with no gathering actor.
 */
export async function publishRoundTally(
  eventId: string,
  roundId: string,
  phase: RoundPhase,
): Promise<{ ok: boolean; error?: string }> {
  try {
    const [event] = await sql<{ actor_did: string | null }[]>`select actor_did from events where id = ${eventId}`
    if (!event?.actor_did) return { ok: true }
    const { publishTally } = await import('@/lib/atproto/tally')
    const out = await publishTally({ eventId, callerUserId: null, round: phase, roundId })
    const failed = out.results.filter((r) => r.error)
    if (failed.length) {
      const error = failed.map((r) => `${r.kind} ${r.id}: ${r.error}`).join('; ')
      console.error(`[voting] tally publication for round ${roundId} had errors: ${error}`)
      return { ok: false, error }
    }
    return { ok: true }
  } catch (e) {
    const error = e instanceof Error ? e.message : String(e)
    console.error(`[voting] tally publication for round ${roundId} failed: ${error}`)
    return { ok: false, error }
  }
}

/** SQL predicate: this unfinalized round must be closed now. */
function dueRounds(t: Sql, eventId?: string) {
  return t<{ id: string }[]>`
    select r.id
    from vote_rounds r
    join events e on e.id = r.event_id
    where r.finalized_at is null
      ${eventId ? t`and r.event_id = ${eventId}` : t``}
      and (
        r.closes_at <= now()
        or (r.phase = 'pre-event' and e.status not in ${t(KEEP_OPEN_STATUSES['pre-event'] as string[])})
        or (r.phase = 'attendance' and e.status not in ${t(KEEP_OPEN_STATUSES.attendance as string[])})
      )
    order by r.closes_at
  `
}

/**
 * The job sweep (`/api/jobs/close-rounds`): close every round past `closes_at` or whose
 * event has left the voting phase, publishing each tally after its commit.
 */
export async function closeDueRounds(): Promise<{ closed: CloseRoundResult[]; failed: Array<{ roundId: string; error: string }> }> {
  const due = await dueRounds(sql)
  const closed: CloseRoundResult[] = []
  const failed: Array<{ roundId: string; error: string }> = []
  for (const { id } of due) {
    try {
      const r = await closeRound(id, { publish: 'await' })
      if (r.closed) closed.push(r)
    } catch (e) {
      failed.push({ roundId: id, error: e instanceof Error ? e.message : String(e) })
    }
  }
  return { closed, failed }
}

/* ─────────────────────────────── read ─────────────────────────────── */

async function closeDueForEvent(eventId: string): Promise<void> {
  const due = await dueRounds(sql, eventId)
  for (const { id } of due) {
    // A read must not wait on the PDS; the sweep retries nothing it did not own, so
    // publication here runs in the background.
    await closeRound(id, { publish: 'background' })
  }
}

/**
 * The event's current round: the earliest unfinalized round if there is one
 * ('upcoming' or 'open'), else the most recently finalized ('closed'), else 'none'.
 * Rounds that are due are finalized first, so a round past its window never reads as open.
 */
export async function roundState(eventId: string): Promise<RoundStateResult> {
  if (!isUuid(eventId)) return { round: null, status: 'none' }
  await closeDueForEvent(eventId)
  const [open] = await sql<RoundRow[]>`
    select ${ROUND_COLUMNS(sql)} from vote_rounds r
    where r.event_id = ${eventId} and r.finalized_at is null
    order by r.opens_at asc limit 1
  `
  if (open) {
    const round = toRoundInfo(open)
    return { round, status: round.status }
  }
  const [closed] = await sql<RoundRow[]>`
    select ${ROUND_COLUMNS(sql)} from vote_rounds r
    where r.event_id = ${eventId} and r.finalized_at is not null
    order by r.finalized_at desc limit 1
  `
  return closed ? { round: toRoundInfo(closed), status: 'closed' } : { round: null, status: 'none' }
}

/** One round of the event by id (any status), or null. Due rounds are finalized first. */
export async function getRound(eventId: string, roundId: string): Promise<RoundInfo | null> {
  if (!isUuid(eventId) || !isUuid(roundId)) return null
  await closeDueForEvent(eventId)
  const [row] = await sql<RoundRow[]>`
    select ${ROUND_COLUMNS(sql)} from vote_rounds r where r.id = ${roundId} and r.event_id = ${eventId}
  `
  return row ? toRoundInfo(row) : null
}

/**
 * The finalized round whose outcome may be read, or null when the event has none.
 * Throws `RoundOpenError` when `roundId` (or, without one, any round of the event) is
 * open — an upcoming round with no votes yet does not hide an earlier finalized one.
 */
async function resolveClosedRound(eventId: string, roundId?: string): Promise<RoundInfo | null> {
  if (roundId) {
    const round = await getRound(eventId, roundId)
    if (!round) throw new VotingError('Voting round not found', 404, 'NotFound')
    if (round.status !== 'closed') throw new RoundOpenError(round.id)
    return round
  }
  const state = await roundState(eventId)
  if (state.status === 'open' && state.round) throw new RoundOpenError(state.round.id)
  if (state.status === 'closed') return state.round
  const [closed] = await sql<RoundRow[]>`
    select ${ROUND_COLUMNS(sql)} from vote_rounds r
    where r.event_id = ${eventId} and r.finalized_at is not null
    order by r.finalized_at desc limit 1
  `
  return closed ? toRoundInfo(closed) : null
}

/**
 * Organizer-only raw results of the latest finalized round (or `roundId`): per session
 * voters/votes/credits, most votes first. Throws `RoundOpenError` while open. Callers
 * must have authorized the organizer; this function does not know who is asking.
 */
export async function organizerResults(eventId: string, options: { roundId?: string } = {}): Promise<SessionResult[]> {
  const round = await resolveClosedRound(eventId, options.roundId)
  if (!round) return []
  const rows = await sql<{ session_id: string; voters: number; votes: number; credits: number }[]>`
    select session_id, voters, votes, credits from vote_round_results
    where round_id = ${round.id} and event_id = ${eventId}
    order by votes desc, credits desc, session_id
  `
  return rows.map((r) => ({ sessionId: r.session_id, voters: r.voters, votes: r.votes, credits: r.credits }))
}

/**
 * Auto-scheduler inputs (spec §5.4): per session, total votes and the set of ballot
 * tokens (hex) that named it, for Jaccard overlap. Tokens link a participant's entries to
 * each other and to nobody. Throws `RoundOpenError` while open.
 */
export async function schedulingInputs(eventId: string, options: { roundId?: string } = {}): Promise<SchedulingInputs> {
  const round = await resolveClosedRound(eventId, options.roundId)
  const bySession = new Map<string, { votes: number; tokens: Set<string> }>()
  if (!round) return { roundId: null, bySession }
  const rows = await sql<{ session_id: string; votes: number; token: string }[]>`
    select session_id, votes, encode(ballot_token, 'hex') as token
    from vote_entries where round_id = ${round.id} and event_id = ${eventId}
  `
  for (const r of rows) {
    const agg = bySession.get(r.session_id) ?? { votes: 0, tokens: new Set<string>() }
    agg.votes += r.votes
    agg.tokens.add(r.token)
    bySession.set(r.session_id, agg)
  }
  return { roundId: round.id, bySession }
}

/** Apply k: an entry named by fewer than k ballots carries no counts at all. */
export function suppressEntries(results: readonly SessionResult[], k: number): TallyEntry[] {
  if (!Number.isInteger(k) || k < 1) throw new Error(`k must be a positive integer, got ${k}`)
  return [...results]
    .sort((a, b) => a.sessionId.localeCompare(b.sessionId))
    .map((r) =>
      r.voters < k
        ? { sessionId: r.sessionId, suppressed: true as const }
        : { sessionId: r.sessionId, suppressed: false as const, voters: r.voters, votes: r.votes, credits: r.credits },
    )
}

/**
 * The public, k-suppressed tally of the latest finalized round (or `roundId`); null when
 * the event has no finalized round. Throws `RoundOpenError` while open. `k` defaults to
 * the event's policy `feedbackK`.
 */
export async function publicTally(
  eventId: string,
  k?: number,
  options: { roundId?: string } = {},
): Promise<PublicTally | null> {
  const round = await resolveClosedRound(eventId, options.roundId)
  if (!round) return null
  const threshold = k ?? (await eventK(eventId))
  const [results, [ballots]] = await Promise.all([
    sql<{ session_id: string; voters: number; votes: number; credits: number }[]>`
      select session_id, voters, votes, credits from vote_round_results
      where round_id = ${round.id} and event_id = ${eventId}
    `,
    sql<{ n: number }[]>`select count(*)::int as n from vote_ballots where round_id = ${round.id} and event_id = ${eventId}`,
  ])
  const entries = suppressEntries(
    results.map((r) => ({ sessionId: r.session_id, voters: r.voters, votes: r.votes, credits: r.credits })),
    threshold,
  )
  return { round, k: threshold, ballotsCast: ballots?.n ?? 0, entries }
}
